// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkzlyvhtwaxnmmfhowzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJremx5dmh0d2F4bm1tZmhvd3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTk1NjgsImV4cCI6MjA2NTc3NTU2OH0.dfXk55SAOgXl2X6Or7nqQzVG1bK1kGtP8W_z8_wGCB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);